import com.vanniktech.maven.publish.AndroidSingleVariantLibrary

plugins {
    id "com.vanniktech.maven.publish" version "0.33.0"
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdkVersion = rootProject.ext.compileSdkVersion
    buildToolsVersion = rootProject.ext.buildToolsVersion

    namespace 'com.monri.android'

    buildFeatures {
        buildConfig = true
    }

    repositories {
        maven { url 'https://repo1.maven.org/maven2' }
    }

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 36
        versionCode 1
        versionName rootProject.ext.monriSdkVersion

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            buildConfigField "String", 'MONRI_SDK_VERSION', "\"${rootProject.ext.monriSdkVersion}\""

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            buildConfigField "String", 'MONRI_SDK_VERSION', "\"${rootProject.ext.monriSdkVersion}\""
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])

    api 'androidx.annotation:annotation:1.8.0'
    api "androidx.appcompat:appcompat:1.6.1"
    // Api for this import because we use reflection to alter TextInputLayout
    api "com.google.android.material:material:1.12.0"
    implementation 'androidx.core:core-ktx:1.15.0'

    compileOnly "javax.annotation:jsr250-api:${rootProject.ext.javaAnnotationVersion}"

    implementation "com.google.android.gms:play-services-wallet:$googlePlayServicesWalletVersion"

    testImplementation("org.assertj:assertj-core:3.25.0")
    testImplementation "junit:junit:${rootProject.ext.junitVersion}"
    testImplementation "org.mockito:mockito-core:${rootProject.ext.mockitoCoreVersion}"
    testImplementation "org.robolectric:robolectric:${rootProject.ext.robolectricVersion}"

    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test:rules:1.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-web:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    configure(new AndroidSingleVariantLibrary("release", false, false))

    def groupId = 'com.monri'
    def artifactId = 'monri-android'
    def version = rootProject.ext.monriSdkVersion

    coordinates(groupId, artifactId, version)

    pom {
        name = 'Monri'
        description = 'Monri Android SDK'
        url = 'https://github.com/MonriPayments/monri-android'
        licenses {
            license {
                name = 'MIT License'
                url = 'https://github.com/MonriPayments/monri-android/blob/master/LICENSE'
            }
        }
        developers {
            developer {
                id = 'jasminsuljic'
                name = 'Jasmin Suljic'
                email = 'jasmin.suljic@monri.com'
            }
            developer {
                id = 'adnanomerovic'
                name = 'Adnan Omerovic'
                email = 'adnan.omerovic@monri.com'
            }
        }
        scm {
            connection = 'https://github.com/MonriPayments/monri-android'
            developerConnection = 'git@github.com:MonriPayments/monri-android.git'
            url = 'https://github.com/MonriPayments/monri-android'
        }
    }
}

