// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        kotlin_version = '2.1.0'
    }
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    buildToolsVersion = "36.0.0"
    compileSdkVersion = 36

    javaAnnotationVersion = "1.0"
    junitVersion = "4.13.2"
    mockitoCoreVersion = "3.9.0"
    robolectricVersion = '4.16'
    monriSdkVersion = '3.2.3'

    googlePlayServicesWalletVersion = '19.4.0'
}
